name: Build application

on: [pull_request]

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - run: |
        & dotnet tool update --global uno.check --version 1.12.1
        & uno-check -v --ci --non-interactive --fix
      name: Run Uno Check

    - name: Restore
      run: msbuild -t:restore ReproApp.sln

    - name: Build
      run: msbuild -m ReproApp.sln
